# IMPORTANT LIBRARIES
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt

mpl.style.use(['ggplot'])

# READING london_crime_by_lsoa CSV FILE USING PANDAS
df = pd.read_csv('london_crime_by_lsoa.csv')

# RENAMING borough COLUMN TO District
df.rename(columns={'borough': 'District'}, inplace=True)

"""
CREATE A COPY OF THE DATAFRAME
FOR FURTHER ALTERCATIONS
"""
df1 = df.copy()
"""
REMOVE THE lsoa_code' & 'minor_category COLUMNS
BECAUSE ITS NOT THE CURRENT CONCERN
"""
df1.drop(['lsoa_code', 'minor_category'], axis=1, inplace=True)

"""
CREATING A PIVOT TABLE THAT ONLY SHOWS
MAJOR CRIME AND ITS NUMBER
"""
table = df1.pivot_table(values='value',
                        index=['year'],
                        columns=['major_category'],
                        aggfunc=np.sum,
                        fill_value=0)

# HISTOGRAM
count, bin_edges = np.histogram(table, 15)
table.plot(kind='hist',
           figsize=(15, 6),
           bins=15,
           alpha=0.6,
           xticks=bin_edges
           )

# HISTOGRAM TITLE
plt.title('Histogram of major criminal in 2008-2016')
plt.ylabel('Number of Years')
plt.xlabel('Number of Criminal ')

plt.show()

# BAR CHARTS
table_bar = table['Drugs']
table_bar.plot(kind='bar', figsize=(10, 6))

plt.xlabel('Year')
plt.ylabel('Number of crime drugs')
plt.title('London drugs case in 2008-2016')

plt.show()

# PIE CHARTS
table_pie = table.transpose()
table_pie['All Crime'] = table.sum()
table_pie

# COLORS FOR EACH PIE
colors_list = ['#800000', '#9A6324', '#ffe119',
               '#aaffc3', '#911eb4', '#a9a9a9',
               '#4363d8', '#f58231', '#fabed4']

# HOW EACH PIE SHOULD BE SHOWN
explode_list = [0.1, 0, 0, 0, 0, 0, 0, 0.1, 0.1]

"""
THE RATIO BETWEEN THE CENTER OF EACH PIE SLICE
AND THE START OF THE TEXT GENERATED BY AUTOPCT
"""
table_pie['All Crime'].plot(kind='pie',
                            figsize=(15, 6),
                            autopct='%1.1f%%',
                            startangle=90,
                            shadow=True,
                            labels=None,
                            colors=colors_list,
                            pctdistance=1.12,
                            explode=explode_list)

# SCALE TITLE BY 12% TO MATCH PCTDISTANCE
plt.title('Major Criminal Case in London (2008-2016)', y=1.12)

plt.axis('equal')
plt.legend(labels=table_pie.index, loc='upper left')

plt.show()

# BOX PLOT

table_bar.plot(kind='box', figsize=(8, 6))
plt.title('Drugs Case in London from 1980 to 2013')
plt.ylabel('Number of Cases')

plt.show()

# SCATTER PLOTS
table_scatter = table[['Drugs', 'Robbery']]
table_scatter = table_scatter.reset_index()

ax1 = table_scatter.plot(kind='scatter',
                         x='year',
                         y='Drugs',
                         figsize=(10, 6),
                         color='darkblue',
                         label='Drugs')

ax2 = table_scatter.plot(kind='scatter',
                         x='year',
                         y='Robbery',
                         figsize=(10, 6),
                         color='red',
                         label='Robbery',
                         ax=ax1)

plt.title('Comparing Drugs & Robbery Cases in London From 2008 To 2016')
plt.xlabel('Year')
plt.ylabel('Number of Cases')
plt.show()
